repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: v3.8.3
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        name: Check variable types (mypy)
        files: ^fact_inventory/
        additional_dependencies:
          - advanced-alchemy
          - litestar
          - pydantic
          - pydantic_settings

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.409
    hooks:
      - id: pyright
        name: Check variable types (pyright)
        files: ^fact_inventory/
