"""ASGI middleware that stamps every HTTP response with a traceparent header.

Adds the W3C Trace Context ``traceparent`` header (see
``fact_inventory.lib.otel.get_traceparent_header``) to every outgoing HTTP
response for registered routes, including responses generated by validation
errors or handler-raised exceptions. This allows clients and downstream
systems to correlate a response with the server-side trace/span that
produced it.

Notes
-----
This middleware must wrap the fully assembled ``Litestar.asgi_handler``
directly (see ``fact_inventory.server.app.create_app``), rather than being
registered via the app's ``middleware=[...]`` list. Middleware in that
list is resolved per-route and sits *inside* other middleware (such as
rate limiting) that may raise an exception before delegating to the next
ASGI app in the chain. Such exceptions bypass any per-route middleware's
``send`` wrapper entirely. Wrapping ``asgi_handler`` directly makes this
middleware the outermost layer, guaranteeing it observes every response:
success, validation errors, handler-raised exceptions, and rejections
raised by other middleware (e.g. rate limiting).
"""

from litestar.enums import ScopeType
from litestar.middleware import ASGIMiddleware
from litestar.types import ASGIApp, Message, Receive, Scope, Send

from fact_inventory.lib.otel import get_traceparent_header

__all__ = ["TraceparentMiddleware"]

_TRACEPARENT_HEADER = b"traceparent"


class TraceparentMiddleware(ASGIMiddleware):
    """Stamp every HTTP response with the current W3C traceparent header.

    Any pre-existing ``traceparent`` header on the outgoing response is
    replaced, so the value always reflects the server's active trace/span
    context rather than a value set upstream or by a handler.
    """

    scopes = (ScopeType.HTTP,)

    async def handle(
        self,
        scope: Scope,
        receive: Receive,
        send: Send,
        next_app: ASGIApp,
    ) -> None:
        """Wrap ``send`` to inject the traceparent header on response start.

        Parameters
        ----------
        scope : Scope
            The ASGI connection scope.
        receive : Receive
            The ASGI receive callable.
        send : Send
            The ASGI send callable.
        next_app : ASGIApp
            The next ASGI application in the middleware stack to call.
        """

        async def send_wrapper(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = [
                    (name, value)
                    for name, value in message.get("headers", [])
                    if name.lower() != _TRACEPARENT_HEADER
                ]
                headers.append((_TRACEPARENT_HEADER, get_traceparent_header().encode()))
                message["headers"] = headers
            await send(message)

        await next_app(scope, receive, send_wrapper)
