"""Database access layer for the ``fact_inventory`` table."""

import logging
from collections.abc import Sequence
from typing import Any

from advanced_alchemy.repository import SQLAlchemyAsyncRepository
from sqlalchemy import CursorResult, delete, func, select, tuple_
from sqlalchemy.engine import Result
from sqlalchemy.sql import Select

from fact_inventory.domain.retention.history import HistoryRetentionPolicy
from fact_inventory.domain.retention.time import TimeRetentionPolicy
from fact_inventory.infrastructure.db.models.fact_inventory import FactInventory

__all__ = ["FactInventoryRepository"]

logger = logging.getLogger(__name__)


class FactInventoryRepository(SQLAlchemyAsyncRepository[FactInventory]):
    """Database access layer for the fact_inventory table.

    Methods here contain database-specific query logic (raw SQL
    constructs, dialect hints, etc.). Application rules belong in
    FactInventoryService.

    Notes
    -----
    Retention deletes run in bounded batches and commit after each batch.
    Committing per batch keeps individual transactions short so that row
    locks are released promptly and dead tuples do not accumulate for the
    duration of a large backlog cleanup. The batch boundary is therefore a
    transaction boundary: a failure partway through leaves the rows deleted
    by earlier batches in place rather than rolling them back.
    """

    model_type = FactInventory
    # Keep delete transactions bounded for accumulated retention backlogs.
    RETENTION_BATCH_SIZE = 1000

    async def insert_record(self, data: dict[str, Any]) -> FactInventory:
        """Insert a new fact inventory record into the database.

        Creates a new record with the provided fact data. Multiple rows may
        exist for the same client_address - each call creates a new row with
        a unique UUID generated by the database.

        Parameters
        ----------
        data : dict[str, Any]
            Dictionary containing client_address, system_facts,
            package_facts, local_facts, and client_facts.

        Returns
        -------
        FactInventory
            The created record instance with all attributes populated.

        Raises
        ------
        RepositoryError
            If the record could not be created (e.g., database connection error).
        SQLAlchemyError
            If database persistence fails for any reason.
        """
        instance = self.model_type(**data)
        result = await self.add(instance)
        logger.info("New fact record inserted")
        return result

    async def _delete_batch(self, keys: Sequence[tuple[Any, str]]) -> int:
        """Delete one batch of rows identified by ``(id, client_address)``.

        Including ``client_address`` (the partition key) in the predicate lets
        PostgreSQL prune the delete to the single partition holding each row.

        Parameters
        ----------
        keys : Sequence[tuple[Any, str]]
            Non-empty ``(id, client_address)`` primary-key pairs to delete.
            Callers select a batch first and only invoke this when rows exist.

        Returns
        -------
        int
            Number of rows actually deleted (never negative).
        """
        stmt = delete(self.model_type).where(
            tuple_(self.model_type.id, self.model_type.client_address).in_(keys)
        )
        result: Result[Any] = await self.session.execute(stmt)
        rowcount = result.rowcount if isinstance(result, CursorResult) else 0
        return max(rowcount, 0)

    async def _delete_in_batches(self, batch_query: Select[tuple[Any, str]]) -> int:
        """Run ``batch_query`` and delete the selected rows, batch by batch.

        Each iteration selects up to ``RETENTION_BATCH_SIZE`` primary-key
        pairs, deletes them, and commits before selecting the next batch. The
        loop stops when a select returns no rows.

        Parameters
        ----------
        batch_query : Select[tuple[Any, str]]
            A select of ``(id, client_address)`` pairs for rows eligible for
            deletion. It must already apply the batch-size limit.

        Returns
        -------
        int
            Total number of rows deleted across all batches.
        """
        deleted_count = 0
        while True:
            async with self.session.begin():
                rows = await self.session.execute(batch_query)
                keys = [(row.id, row.client_address) for row in rows]
                if not keys:
                    break
                deleted_count += await self._delete_batch(keys)
        if deleted_count:
            logger.info("Record pruning completed")
        return deleted_count

    def _expired_keys_query(
        self, policy: TimeRetentionPolicy
    ) -> Select[tuple[Any, str]]:
        """Build the batch query selecting expired ``(id, client_address)`` keys."""
        return (
            select(self.model_type.id, self.model_type.client_address)
            .where(self.model_type.updated_at < policy.cutoff_datetime)
            .limit(self.RETENTION_BATCH_SIZE)
        )

    def _excess_history_keys_query(
        self, policy: HistoryRetentionPolicy
    ) -> Select[tuple[Any, str]]:
        """Build the batch query selecting excess-history ``(id, client_address)`` keys.

        Only clients that currently hold more than ``max_entries`` rows are
        ranked, so the window function does not scan the whole table.
        """
        max_entries = policy.max_entries
        over_limit = (
            select(self.model_type.client_address)
            .group_by(self.model_type.client_address)
            .having(func.count() > max_entries)
            .subquery()
        )
        row_num = func.row_number().over(
            partition_by=self.model_type.client_address,
            order_by=(
                self.model_type.updated_at.desc(),
                self.model_type.id.desc(),
            ),
        )
        ranked = (
            select(
                self.model_type.id,
                self.model_type.client_address,
                row_num.label("rn"),
            )
            .where(self.model_type.client_address.in_(select(over_limit)))
            .subquery()
        )
        return (
            select(ranked.c.id, ranked.c.client_address)
            .where(ranked.c.rn > max_entries)
            .limit(self.RETENTION_BATCH_SIZE)
        )

    async def delete_facts_older_than(self, policy: TimeRetentionPolicy) -> int:
        """Delete expired fact records in bounded batches.

        Parameters
        ----------
        policy : TimeRetentionPolicy
            Time retention policy providing the cutoff datetime.

        Returns
        -------
        int
            Total number of rows deleted across all batches.

        Raises
        ------
        RepositoryError
            If the record could not be deleted (e.g., database connection error).
        SQLAlchemyError
            If database persistence fails for any reason.
        """
        return await self._delete_in_batches(self._expired_keys_query(policy))

    async def delete_old_client_facts_over_limit(
        self, policy: HistoryRetentionPolicy
    ) -> int:
        """Delete excess history per client_address in bounded batches.

        Keeps the newest max_entries per client_address by using a window
        function to rank records within each client_address partition, then
        deleting those beyond the policy's max_entries threshold.

        Parameters
        ----------
        policy : HistoryRetentionPolicy
            History retention policy specifying maximum records per client_address.

        Returns
        -------
        int
            Total number of rows deleted across all batches.

        Raises
        ------
        RepositoryError
            If the record could not be deleted (e.g., database connection error).
        SQLAlchemyError
            If database persistence fails for any reason.
        """
        return await self._delete_in_batches(self._excess_history_keys_query(policy))
