---
- name: Gather ansible system facts
  become: "{{ fact_inventory_gather_facts_become | bool }}"
  ansible.builtin.setup:
    gather_subset: "{{ fact_inventory_gather_facts_subset }}"
    fact_path: "{{ fact_inventory_gather_local_facts_dir }}"

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: "{{ fact_inventory_gather_package_manager }}"
